#!/usr/bin/env node
// Emit a DTCG-subset tokens.json in a stack-native format.
import { resolve } from "node:path";
import { runCli, isMain, UsageError } from "./lib/cli.mjs";
import { readText } from "./lib/fs.mjs";
import { flatten, groupTokens, parseDimension, parseDuration, parseEasing, cssValue, darkOf, textMetrics } from "./lib/tokens.mjs";
import { toHex } from "./lib/contrast.mjs";

const HELP = `
Usage: emit-tokens.mjs --in <tokens.json> [--format css|tailwind4|tailwind3|mui|json|js] [--root <dir>]

Prints the tokens in the requested format to stdout:
  css        :root vars + ".dark, [data-theme=dark]" + prefers-color-scheme dark block
  tailwind4  @theme { ... } + the same dark override blocks (spacing aliases as --spacing-*)
  tailwind3  module.exports = { theme: { extend: {...} } } referencing the CSS vars (emit css too)
  mui        createTheme-shaped JSON (palette, colorSchemes.light/dark, typography incl. h1..caption/overline
             variants with lineHeight + letterSpacing, shape, transitions)
  json       {"light": {"--var": value}, "dark": {...}}
  js         motion-tokens ES module for JS animation (Motion, WAAPI, transition props, timers):
             ms(name), sec(name), ease(name), durations, easings. Reads the live --duration-*/--ease-*
             variable, falls back to the token value (server, tests); unknown names throw
Variable names: --color-* --font-* --text-* (+ --text-*--line-height, --text-*--letter-spacing) --tracking-*
--space-* --radius-* --shadow-* --duration-* --ease-*.

Options:
  --in <file>      tokens file (relative to --root)
  --format <fmt>   default css
  --root <dir>     base dir for --in (default: cwd)
  --help
`;

const FORMATS = ["css", "tailwind4", "tailwind3", "mui", "json", "js"];

function block(selector, decls, indent = "") {
  return `${indent}${selector} {\n${decls.map((d) => `${indent}  ${d}`).join("\n")}\n${indent}}`;
}

function darkBlocks(rows) {
  const dark = rows.filter((r) => r.dark != null).map((r) => `${r.varName}: ${r.dark};`);
  if (!dark.length) return "";
  return "\n\n" + block('.dark, [data-theme="dark"]', dark) + "\n\n@media (prefers-color-scheme: dark) {\n" +
    block(':root:not(.light):not([data-theme="light"])', dark, "  ") + "\n}";
}

function lightDecls(rows) {
  const out = [];
  for (const r of rows) {
    out.push(`${r.varName}: ${r.light};`);
    if (r.group === "text") for (const m of textMetrics(r.token)) out.push(`${r.varName}--${m.suffix}: ${m.value};`);
  }
  return out;
}

export function emitCss(tokens) {
  const rows = flatten(tokens);
  return "/* generated by finally-good-ui emit-tokens.mjs from tokens.json; edit the tokens, not this block */\n" +
    block(":root", lightDecls(rows)) + darkBlocks(rows) + "\n";
}

export function emitTailwind4(tokens) {
  const rows = flatten(tokens);
  const decls = lightDecls(rows);
  for (const r of rows.filter((x) => x.group === "space")) decls.push(`--spacing-${r.name}: var(${r.varName});`);
  return "/* generated by finally-good-ui emit-tokens.mjs; paste after @import \"tailwindcss\" */\n" +
    block("@theme", decls) + darkBlocks(rows) + "\n";
}

export function emitTailwind3(tokens) {
  const rows = flatten(tokens);
  const KEYS = { color: "colors", font: "fontFamily", text: "fontSize", tracking: "letterSpacing", space: "spacing",
    radius: "borderRadius", shadow: "boxShadow", duration: "transitionDuration", easing: "transitionTimingFunction" };
  const extend = {};
  for (const r of rows) {
    const k = KEYS[r.group];
    let v = `var(${r.varName})`;
    if (r.group === "text") {
      // Tailwind 3 fontSize tuple: [size, { lineHeight, letterSpacing }]
      const metrics = Object.fromEntries(textMetrics(r.token).map((m) => [m.prop, `var(${r.varName}--${m.suffix})`]));
      if (Object.keys(metrics).length) v = [v, metrics];
    }
    (extend[k] ||= {})[r.name] = v;
  }
  const body = Object.entries(extend).map(([k, obj]) =>
    `      ${k}: {\n${Object.entries(obj).map(([n, v]) => `        ${JSON.stringify(n)}: ${JSON.stringify(v)},`).join("\n")}\n      },`).join("\n");
  return "// generated by finally-good-ui emit-tokens.mjs. Requires the CSS variables from --format css.\n" +
    "module.exports = {\n  darkMode: [\"class\"],\n  theme: {\n    extend: {\n" + body + "\n    },\n  },\n};\n";
}

export function emitJson(tokens) {
  const rows = flatten(tokens);
  const light = {}, dark = {};
  for (const r of rows) {
    light[r.varName] = r.light;
    if (r.group === "text") for (const m of textMetrics(r.token)) light[`${r.varName}--${m.suffix}`] = m.value;
    if (r.dark != null) dark[r.varName] = r.dark;
  }
  return { light, dark };
}

export function emitJs(tokens) {
  const durs = Object.fromEntries([...groupTokens(tokens?.duration)].map(([n, t]) => [n, parseDuration(t.$value)?.value]).filter(([, v]) => v != null));
  const eases = Object.fromEntries([...groupTokens(tokens?.easing)].map(([n, t]) => [n, parseEasing(t.$value)]).filter(([, v]) => v));
  return `// generated by finally-good-ui emit-tokens.mjs from tokens.json (--format js); edit the tokens, not this file.
// Motion tokens for JS (Motion, WAAPI, Svelte/Vue transition props, timers that wait on a transition).
// Call when animating, not at module load: the live CSS variable wins (theme and reduced-motion overrides),
// the token value is the fallback (server rendering, tests).
const DURATIONS = ${JSON.stringify(durs)};
const EASINGS = ${JSON.stringify(eases)};
const cssVar = (n) => (typeof document === "undefined" ? "" : getComputedStyle(document.documentElement).getPropertyValue(n).trim());
const known = (map, kind, name) => { if (!Object.hasOwn(map, name)) throw new Error(\`unknown \${kind} token "\${name}"\`); };

export const durations = Object.keys(DURATIONS);
export const easings = Object.keys(EASINGS);

/** Duration in ms: ms("standard") -> 250. */
export function ms(name) {
  known(DURATIONS, "duration", name);
  const live = cssVar(\`--duration-\${name}\`);
  const n = parseFloat(live);
  if (!Number.isFinite(n)) return DURATIONS[name];
  return /ms$/.test(live) ? n : /s$/.test(live) ? n * 1000 : n;
}

/** Duration in seconds (Motion): sec("standard") -> 0.25. */
export const sec = (name) => ms(name) / 1000;

/** Cubic-bezier control points: ease("move") -> [0.2, 0, 0, 1]. */
export function ease(name) {
  known(EASINGS, "easing", name);
  const live = cssVar(\`--ease-\${name}\`);
  if (live === "linear") return [0, 0, 1, 1];
  const pts = live.match(/-?[\\d.]+/g);
  return pts && pts.length === 4 ? pts.map(Number) : EASINGS[name];
}
`;
}

export function emitMui(tokens) {
  const colors = Object.fromEntries(groupTokens(tokens?.color));
  const hex = (name, mode) => {
    const t = colors[name];
    if (!t) return undefined;
    const v = mode === "dark" ? darkOf(t) ?? t.$value : t.$value;
    return toHex(v) ?? v;
  };
  const palette = (mode) => {
    const p = { mode };
    const set = (key, obj) => { const clean = Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined)); if (Object.keys(clean).length) p[key] = clean; };
    set("primary", { main: hex("primary", mode), contrastText: hex("primary-foreground", mode) });
    set("secondary", { main: hex("secondary", mode) ?? hex("accent", mode), contrastText: hex("secondary-foreground", mode) ?? hex("accent-foreground", mode) });
    set("error", { main: hex("destructive", mode), contrastText: hex("destructive-foreground", mode) });
    set("success", { main: hex("success", mode), contrastText: hex("success-foreground", mode) });
    set("warning", { main: hex("warning", mode), contrastText: hex("warning-foreground", mode) });
    set("info", { main: hex("info", mode), contrastText: hex("info-foreground", mode) });
    set("background", { default: hex("background", mode), paper: hex("card", mode) ?? hex("background", mode) });
    set("text", { primary: hex("foreground", mode), secondary: hex("muted-foreground", mode) });
    const divider = hex("border", mode);
    if (divider) p.divider = divider;
    return p;
  };
  const light = palette("light"), dark = palette("dark");

  const fonts = Object.fromEntries(groupTokens(tokens?.font));
  const fontTok = fonts.sans ?? fonts.body ?? Object.values(fonts)[0];
  const texts = Object.fromEntries(groupTokens(tokens?.text));
  const px = (d) => (d ? (d.unit === "rem" ? d.value * 16 : d.value) : undefined);
  const typography = {};
  if (fontTok) typography.fontFamily = cssValue("font", fontTok.$value);
  if (fonts.mono) typography.fontFamilyMonospace = cssValue("font", fonts.mono.$value);
  const base = texts.base ?? texts.md;
  if (base) typography.fontSize = px(parseDimension(base.$value));
  // Variants carry the per-step metrics (craft.tracking-by-size). Mapped by the default step names.
  const variant = (tok) => {
    const d = parseDimension(tok.$value);
    const v = d ? { fontSize: `${Math.round((px(d) / 16) * 10000) / 10000}rem` } : {};
    for (const m of textMetrics(tok)) v[m.prop] = m.prop === "lineHeight" ? Number(m.value) : m.value;
    return v;
  };
  const VARIANTS = { h1: "6xl", h2: "5xl", h3: "4xl", h4: "3xl", h5: "2xl", h6: "xl", subtitle1: "lg",
    body1: texts.base ? "base" : "md", body2: "sm", caption: "xs" };
  for (const [mui, ours] of Object.entries(VARIANTS)) if (texts[ours]) typography[mui] = variant(texts[ours]);
  const caps = Object.fromEntries(groupTokens(tokens?.tracking)).caps;
  if (caps) typography.overline = { ...(texts.xs ? variant(texts.xs) : {}), textTransform: "uppercase", letterSpacing: cssValue("tracking", caps.$value) };

  const radii = Object.fromEntries(groupTokens(tokens?.radius));
  const r = radii.md ?? radii.base ?? radii.DEFAULT ?? Object.values(radii).find((t) => (parseDimension(t.$value)?.value ?? 0) > 0);
  const shape = r ? { borderRadius: px(parseDimension(r.$value)) } : {};

  const durs = Object.fromEntries([...groupTokens(tokens?.duration)].map(([n, t]) => [n, parseDuration(t.$value)?.value]));
  const duration = {};
  const map = { shortest: "micro", shorter: "short", short: "standard", standard: "medium", complex: "long", enteringScreen: "standard" };
  for (const [k, ours] of Object.entries(map)) if (durs[ours] != null) duration[k] = durs[ours];
  if (durs.standard != null) duration.leavingScreen = Math.round(durs.standard * 0.7);
  const eases = Object.fromEntries([...groupTokens(tokens?.easing)].map(([n, t]) => [n, t.$value]));
  const easing = {};
  const emap = { easeInOut: "move", easeOut: "enter", easeIn: "exit", sharp: "snappy" };
  for (const [k, ours] of Object.entries(emap)) {
    if (eases[ours] != null) { const e = parseEasing(eases[ours]); easing[k] = e ? `cubic-bezier(${e.join(", ")})` : String(eases[ours]); }
  }
  return {
    palette: light,
    colorSchemes: { light: { palette: light }, dark: { palette: dark } },
    typography,
    shape,
    transitions: { duration, easing },
  };
}

export function emit(tokens, format) {
  switch (format) {
    case "css": return emitCss(tokens);
    case "tailwind4": return emitTailwind4(tokens);
    case "tailwind3": return emitTailwind3(tokens);
    case "mui": return emitMui(tokens);
    case "json": return emitJson(tokens);
    case "js": return emitJs(tokens);
    default: throw new UsageError(`unknown --format ${format} (use ${FORMATS.join("|")})`);
  }
}

if (isMain(import.meta.url)) {
  runCli({
    help: HELP,
    spec: { string: ["root", "in", "format"] },
    main: ({ flags }) => {
      const format = flags.format || "css";
      if (!FORMATS.includes(format)) throw new UsageError(`unknown --format ${format} (use ${FORMATS.join("|")})`);
      if (!flags.in) throw new UsageError("--in <tokens.json> is required");
      const file = resolve(flags.root || ".", flags.in);
      const text = readText(file);
      if (text == null) throw new UsageError(`cannot read ${flags.in}`);
      let tokens;
      try { tokens = JSON.parse(text); } catch (e) { throw new UsageError(`invalid JSON in ${flags.in}: ${e.message}`); }
      return emit(tokens, format);
    },
  });
}
